export const APP_STATE = "APP_STATE";

export const FETCH_WEATHER = "FETCH_WEATHER";
export const FETCH_WEATHER_CANCEL = "FETCH_WEATHER_CANCEL";
export const FETCH_WEATHER_SUCCESS = "FETCH_WEATHER_SUCCESS";
export const FETCH_WEATHER_FAILED = "FETCH_WEATHER_FAILED";

export const USER_INPUTS = "USER_INPUTS";
