export enum AppStateTypes {
    APP_STATE = 'APP_STATE'
}

export enum UserInputTypes {
    USER_INPUTS = 'USER_INPUTS'
}

export enum WeatherActionTypes {
    FETCH_WEATHER = 'FETCH_WEATHER',
    FETCH_WEATHER_CANCEL = 'FETCH_WEATHER_CANCEL',
    FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS',
    FETCH_WEATHER_FAILED = 'FETCH_WEATHER_FAILED'
}

export enum WeatherForecastTypes {
    FETCH_FORECAST = 'FETCH_FORECAST',
    FETCH_FORECAST_CANCEL = 'FETCH_FORECAST_CANCEL',
    FETCH_FORECAST_SUCCESS = 'FETCH_FORECAST_SUCCESS',
    FETCH_FORECAST_FAILED = 'FETCH_FORECAST_FAILED'
}
